# Site wide configuration

title: swagger.ed
locale: en_US
description: Change the way you look at APIs
logo: common/site-logo.png
search: false
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Chris Spiliotopoulos
  avatar: authors/chris.jpg
  email: chrysanthos.spiliotopoulos@gmail.com
  disqus-shortname: swaggered
  twitter: chefArchitect
  github: https://github.com/chefArchitect/swagger.ed
  linkedin: #username
 
